[project]
name = "cvp_mcp"
version = "0.1.0"
description = "CloudVision MCP Server"
dependencies = [
    "cloudvision",
    "grpcio",
    "mcp[cli]"
]

[tool.uv.workspace]
members = [
    "cvp-mcp",
]



